workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: 1.11.2
      vars:
        XCODE_WORKSPACE: "Capstone.xcworkspace"
        XCODE_SCHEME: "Capstone"
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install        
      - name: Build debug app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO          
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - ade.reskita@gmail.com